/**
 * Copies the compiled ABIs out of the Foundry artifacts into a typed TS module, so the app
 * and the contracts can never drift apart silently.
 *
 *   npm run abi     (run it after any change under contracts/src)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../../..");
const contracts = ["AgentTreasury", "MockUSD"] as const;

const parts = contracts.map((name) => {
  const artifact = JSON.parse(
    readFileSync(
      resolve(root, `contracts/out/${name}.sol/${name}.json`),
      "utf8",
    ),
  );
  return `export const ${lowerFirst(name)}Abi = ${JSON.stringify(artifact.abi)} as const;`;
});

const header = `// Generated by scripts/abi.ts from the Foundry artifacts. Do not edit by hand.\n// Regenerate with: npm run abi\n\n`;
const out = resolve(import.meta.dirname, "../lib/abi.ts");
writeFileSync(out, header + parts.join("\n\n") + "\n");

console.log(`wrote ${out} (${contracts.join(", ")})`);

function lowerFirst(s: string): string {
  return s[0].toLowerCase() + s.slice(1);
}
